name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'kerwanp'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Build application
        run: |
          yarn
          yarn build:prod
      - name: Generate definition file
        run: node .dist/main.js
      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Trigger VSCode extension CI
        run: |
          curl -XPOST -u "${{ secrets.CORE_PAT_USERNAME}}:${{secrets.CORE_PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/ManticoreGamesInc/vscode-core/actions/workflows/release.yml/dispatches --data '{"ref": "main"}'
